import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-zinc-50 dark:bg-black`}>
        <div className="flex">
          <Nav />
          <main className="min-h-screen flex-1 p-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
